# default config
#baseurl = "https://examplesite.org"
baseurl = "https://idiving2011.github.io/"
languageCode = "en-us"
title = "iDiving"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
weight = 1
name = "學潛水 Dive course"
hasChildren = true

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "自由潛水Level1課程"
  URL = "charming-evening-field.fdlv1"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "自由潛水Level2課程"
  URL = "charming-evening-field.fdlv2"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "自由潛水Level3課程"
  URL = "charming-evening-field.fdlv3"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "自由潛水美人魚課程"
  URL = "charming-evening-field.fdmermaid"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "水肺初階冬季班課程"
  URL = "charming-evening-field.owdwinter"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "水肺初階夏季平日班課程"
  URL = "charming-evening-field.owdweekdays"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "水肺初階夏季假日班課程"
  URL = "charming-evening-field.owdholiday"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "02自由潛水專長課程"
  URL = "../"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "03自由潛水領導級"
  URL = "../"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "04美人魚課程"
  URL = "../"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "05水肺初階課程"
  URL = "../"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "06水肺初階課程"
  URL = "../"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "07水肺專長課程"
  URL = "../"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "08水肺領導級"
  URL = "../"

  [[menu.main]]
  parent = "學潛水 Dive course"
  name = "09技術潛水課程"
  URL = "../"


[[menu.main]]
weight = 2
name = "玩潛水 Fun Dive"
hasChildren = true

  [[menu.main]]
  parent = "玩潛水 Fun Dive"
  name = "01水肺東北角活動"
  URL = "../"

  [[menu.main]]
  parent = "玩潛水 Fun Dive"
  name = "02水肺國內/國外活動"
  URL = "../"

  [[menu.main]]
  parent = "玩潛水 Fun Dive"
  name = "03自潛東北角活動"
  URL = "../"

  [[menu.main]]
  parent = "玩潛水 Fun Dive"
  name = "04自潛墾丁離島/活動"
  URL = "../"

  [[menu.main]]
  parent = "玩潛水 Fun Dive"
  name = "05水肺俱樂部"
  URL = "../"

[[menu.main]]
weight = 3
name = "購潛水 Shopping"
hasChildren = true

  [[menu.main]]
  parent = "購潛水 Shopping"
  name = "01介紹"
  URL = "../"
  
[[menu.main]]
weight = 4
name = "愛潛水 About Us"
hasChildren = true

  [[menu.main]]
  parent = "愛潛水 About Us"
  name = "01iDiving 介紹"
  URL = "../"

  [[menu.main]]
  parent = "愛潛水 About Us"
  name = "02環保里程碑"
  URL = "../"

  [[menu.main]]
  parent = "愛潛水 About Us"
  name = "03推薦裝備"
  URL = "../"

  [[menu.main]]
  parent = "愛潛水 About Us"
  name = "About"
  URL = "about"
  
  [[menu.main]]
  parent = "愛潛水 About Us"
  name = "Contact"
  URL = "contact"
  

# deult parameter
[params]
logo = "images/logo.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "This is meta description"
# Preloader
preloader = true
# search
search = false
# about author
author = ""
author_image = "images/banner-img.png"
bio = "I’m a Freelance Interactive Art Director based in France. Focusing across branding and identity, digital and print."
# Contact info
tel = "(02)28827696"
mobile = "0909 097 696"
email = "info@idiving.com.tw"
address = "111 台北市士林區前港街8號"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"
# Version
Version = "0.0.1"

# Instagram feed
[params.instafeed]
enable = true
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# cookies
[params.cookies]
#enable = true
enable = false
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
url = "#"

[[params.social]]
icon = "ti-twitter-alt"
url = "#"

[[params.social]]
icon = "ti-linkedin"
url = "#"

[[params.social]]
icon = "ti-github"
url = "#"