jobs:
  deploy:
    docker:
      - image: cimg/base    
    steps:
      - attach_workspace:
          at: my-site
      - run: ls -lah my-site

orbs:
  hugo: circleci/hugo@0.2
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: false
          version: '0.62'