# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
global: &global
  working_directory: ~/project
  docker:
    - image: cibuilds/hugo:0.69.1

jobs:
  build_n_deploy:
    <<: *global
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: |
            git submodule sync && git submodule update --init
            git submodule foreach --recursive git pull origin master
            HUGO_ENV=production hugo -v
      - add_ssh_keys:
          fingerprints:
            = "07:1e:a5:48:a2:cc:c6:a6:ce:7f:a7:43:fa:8f:8d:25"
      - run:
          name: "Deploy to github.io"
          command: |
            cd ~/project/public
            git config --global user.email "idiving2011@gmail.com"
            git config --global user.name "idiving2011"
            git add -A
            git commit -m "Deploy from CircleCI"
            git push origin HEAD:master

workflows:
  version: 2
  build_n_deploy:
    jobs:
      - build_n_deploy:
          filters:
            branches:
              only: master